encoding: utf-8
exclude: [vendor]
gh_pages_url_prefix: https://darthcloud.github.io/BlueRetroWebCfg
gh_url_prefix: https://github.com/darthcloud/BlueRetroWebCfg/blob/master
gems:
  - jekyll-sitemap
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
exclude:
  - package.json
  - README.md
  - node_modules
  - Gemfile
  - vendor
